version: '2'
services:
  #mesin1 -- copykan untuk mesin 2,3, dst
  mesin1:
    container_name: progjar-mesin-1
    image: jupyter/scipy-notebook
    user: root
    environment:
      - "GRANT_SUDO=yes"
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
    volumes:
      - ./work:/home/jovyan/work
      - ./script:/script
    command: "sh /script/run.sh"
    ports:
      - "9000:8888"
      - "9010:8889"
    networks:
      progjar-network:
        ipv4_address: 172.16.16.101
  mesin2:
    container_name: progjar-mesin-2
    image: jupyter/scipy-notebook
    user: root
    environment:
      - "GRANT_SUDO=yes"
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
    volumes:
      - ./work:/home/jovyan/work
      - ./script:/script
    command: "sh /script/run.sh"
    ports:
      - "9001:8888"
      - "9011:8889"
    networks:
      progjar-network:
        ipv4_address: 172.16.16.102
  mesin3:
    container_name: progjar-mesin-3
    image: jupyter/scipy-notebook
    user: root
    environment:
      - "GRANT_SUDO=yes"
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
    volumes:
      - ./work:/home/jovyan/work
      - ./script:/script
    command: "sh /script/run.sh"
    ports:
      - "9002:8888"
      - "9012:8889"
    networks:
      progjar-network:
        ipv4_address: 172.16.16.103
  mesin4:
    container_name: progjar-mesin-4
    image: jupyter/scipy-notebook
    user: root
    environment:
      - "GRANT_SUDO=yes"
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
    volumes:
      - ./work:/home/jovyan/work
      - ./script:/script
    command: "sh /script/run.sh"
    ports:
      - "9003:8888"
      - "9013:8889"
    networks:
      progjar-network:
        ipv4_address: 172.16.16.104

networks:
  progjar-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.16.0/24
          gateway: 172.16.16.1

